services:
  # Telegram bot service
  whisper-telegram-bot:
    build:
      context: .
      dockerfile: dockerfile
    # image: ghcr.io/johnr24/telegram-bot:latest
    container_name: telegram-bot
    restart: always
    # depends_on is removed as whisper-api service is removed
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      # WHISPER_API_URL is removed as the bot uses local whisper CLI
      - AUTHORIZED_USERS=${AUTHORIZED_USERS}
    volumes:
      - ./temp:/app/temp 
    networks:
      - network

networks:
  network:
    driver: bridge
