services:
  # Telegram bot service
  whisper-telegram-bot:
    build:
      context: .
      dockerfile: dockerfile
    # image: ghcr.io/johnr24/telegram-bot:latest
    container_name: telegram-bot
    restart: always
    depends_on:
      whisper-api: # Service name as the key
        condition: service_healthy # Wait for whisper-api's healthcheck to pass
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - WHISPER_API_URL=http://whisper-api:9000/asr
      - AUTHORIZED_USERS=${AUTHORIZED_USERS}
    volumes:
      - ./temp:/app/temp 
    networks:
      - network

networks:
  network:
    driver: bridge
